### ISSUE TITLE
Géostandards du CNIG

### ISSUE THREAD

**Issue by loichay** [datagouv/schema.data.gouv.fr#203]
Les instances de gouvernance et l'organisation des travaux du CNIG sont en cours de refonte. Il est notamment prévu que la Commission Données deviennent une Commission Standards. Depuis la disparition de la COVADIS, la création et la maintenance des géostandards sont sous la responsabilité de cette institution. A minima, schema.data.gouv ne devrait-il pas le mentionner dans "Initiatives similaires" ? Les géostandards élaborés sous l'égide du CNIG et une fois validés ne devraient-ils pas, au même titre que les autres schémas de données publiques, être référencés ici ?

**Comment by haubourg** [comment]
Je tombe ici par hasard au grès d'une discussion CNIG. 
Totalement d'accord avec cette convergence de méthode et de standards. On pousse dans le sens d'avoir des espaces Github et des méthodes d'émergence validation des standards similaires à l'OGC ( forge ouverte + implémentations de référence nécessaire pour la validation du standard + animation forte avec code/standard sprints) . Et oui, si on travaillait directement ici, ce serait encore mieux

**Comment by Pierlou** [comment]
Des liens forts sont en train de se tisser entre le CNIG et schema.data.gouv, à la fois pour le [référencement des standards](https://schema.data.gouv.fr/schemas.html?q=&label=CNIG) et pour la création de nouveaux (cf [friches](https://schema.data.gouv.fr/cnigfr/schema-friches/) et [sites économiques](https://schema.data.gouv.fr/cnigfr/schema-sites-economiques/)). L'équipe de data.gouv.fr participe activement à plusieurs GT du CNIG (notamment Référencement des standards et Standard des standards).
cc @GT-CNIG-DDU
