### ISSUE TITLE
Effectifs scolaires

### ISSUE THREAD

**Issue by jmbourgogne** [datagouv/schema.data.gouv.fr#205]
## Description du schéma
Dans le cadre d'une réflexion engagée lors d'un Challenge Data avec Datactivist.st, les collectivités souhaitent proposer un standard de restitution de l'évolution des effectifs scolaires dans les écoles primaires.

## Liens
https://opendatafrance.gitbook.io/scdl/standards-en-cours-delaboration/schema-en-discussion/effectif-des-ecoles

## Stade d'avancement
_Ajoutez un `x`dans les crochets décrivant votre situation. Vous ensuite pouvez supprimer cette ligne._

Mon schéma est :

- [ X] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by Pierlou** [comment]
Bonjour Jean-Marie, où en est la création de ce schéma ? Le lien vers le gitbook semble mort

**Comment by Pierlou** [comment]
Réponse :
> Le standard n’est plus maintenu ni publié car depuis sa conception, le ministère a finalement ouvert les données centralisées (ce qui n’était pas le cas alors).
Les données sont accessibles [ici](https://data.education.gouv.fr/explore/dataset/fr-en-ecoles-effectifs-nb_classes/table/?disjunctive.rentree_scolaire&disjunctive.region_academique&disjunctive.academie&disjunctive.departement&disjunctive.commune&disjunctive.numero_ecole&disjunctive.denomination_principale&disjunctive.patronyme&disjunctive.secteur&disjunctive.code_postal&sort=tri) 
L’outil Dataclic permet d’extraire les données à l’échelle communale (ou EPIC) : https://dataclic.fr/effectif_scolaire
Le gitbook associé est [ici](https://opendatafrance.gitbook.io/evolution-du-socle-commun-des-donnees-locales/standards-en-cours-delaboration/schema-en-discussion/effectif-des-ecoles)
Je pense que l’on peut supprimer (ou archiver) cette entrée dans schéma.data.gouv
