### ISSUE TITLE
Standard GTFS pour les données de transport

### ISSUE THREAD

**Issue by ArthurSrz** [datagouv/schema.data.gouv.fr#296]
## Description du schéma
Le GTFS est aujourd'hui le schéma le plus utilisé pour référencer les données de transports. 

## Liens
[Ici](https://developers.google.com/transit/gtfs?hl=fr)

## Stade d'avancement
_Ajoutez un `x`dans les crochets décrivant votre situation. Vous ensuite pouvez supprimer cette ligne._

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration
- [x] **largement utilisé :** ce schéma est utilisé par un très grand nombre d'acteurs

**Comment by Pierlou** [comment]
Bonjour, quel est votre besoin derrière le référencement du GTFS sur schema.data.gouv ?

**Comment by thbar** [comment]
Point d'attention par rapport à https://transport.data.gouv.fr sur le message politique que ça peut envoyer, je partage ça en équipe ici.

**Comment by thbar** [comment]
> Bonjour, quel est votre besoin derrière le référencement du GTFS sur schema.data.gouv ?

Je me pose la même question. Le GTFS, si il est très utilisé (et très représenté sur https://transport.data.gouv.fr), il est sur une gouvernance différente (https://github.com/google/transit/blob/master/gtfs/CHANGES.md), et l'inclure sur `schema.data.gouv.fr` amènerait à inclure beaucoup d'autres choses (dont au minimum https://normes.transport.data.gouv.fr/ etc).

J'en reparle en interne mais je pense que ça n'est pas forcément le but de `schema.data.gouv.fr` ? Mais qui défini cette ligne éditoriale aujourd'hui d'ailleurs ?

**Comment by Pierlou** [comment]
La ligne éditoriale est à notre main, et nous sommes ouverts à la discussion sur l'incorporation de nouveaux standards sur la plateforme :) L'idée est d'y rassembler ceux qui sont portés par une gouvernance nationale ou répondent à un besoin réglementaire ou à un cas d'usage, afin de favoriser leur découvrabilité et leur adoption. Dans le cas de GTFS, ni l'une ni l'autre ne bénéficieraient d'un portage schema.data.gouv je pense. Une mention dans la page `Initiatives similaires` pourrait s'envisager, mais je ne suis pas convaincu de sa pertinence.
